language: python
python: "2.7"
install:
    - pip install psycopg2
    - cp buildout/* .
    - cp database.cfg.travis database.cfg
    - mkdir -p buildout-cache/eggs
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg
    - bin/buildout -N -t 3 -c travis.cfg
